Modules/CodeEduBook/Http/routes.php
<?php

Route::group(['middleware' => 'auth'], function() {
    Route::resource('categories', 'CategoriesController', ['except' => 'show']);
    Route::resource('books', 'BooksController', ['except' => 'show']);

    Route::group(['prefix' => 'trashed', 'as' => 'trashed.'], function() {
        Route::resource('books', 'BooksTrashedController', ['except' => ['create', 'edit', 'store', 'destroy']]);
    });
});

Modules/CodeEduBook/Models/Book.php
<?php

namespace CodeEduBook\Models;

use CodePub\Models\User;
use Bootstrapper\Interfaces\TableInterface;
use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model implements TableInterface
{
    use FormAccessible;
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'author_id',
        'title',
        'subtitle',
        'price'
    ];

    public function author()
    {
        return $this->belongsTo(User::class);
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTrashed();
    }

    public function formCategoriesAttribute()
    {
        return $this->categories->pluck('id')->all();
    }

    /**
     * A list of headers to be used when a table is displayed
     *
     * @return array
     */
    public function getTableHeaders()
    {
        return ['#', 'Título', 'Autor', 'Preço'];
    }

    /**
     * Get the value for a given header. Note that this will be the value
     * passed to any callback functions that are being used.
     *
     * @param string $header
     * @return mixed
     */
    public function getValueForHeader($header)
    {
        switch ($header) {
            case '#':
                return $this->id;
            case 'Título':
                return $this->title;
            case 'Autor':
                return $this->author->name;
            case 'Preço':
                return $this->price;
        }
    }
}

Modules/CodeEduBook/Http/Controllers/BooksController.php
<?php

namespace CodeEduBook\Http\Controllers;

use CodePub\Http\Controllers\Controller;
use CodeEduBook\Http\Requests\BookCreateRequest;
use CodeEduBook\Http\Requests\BookUpdateRequest;
use CodePub\Models\User;
use CodeEduBook\Repositories\BookRepository;
use CodeEduBook\Repositories\CategoryRepository;
use Illuminate\Http\Request;

class BooksController extends Controller
{
    /**
     * @var BookRepository
     */
    private $book;
    /**
     * @var \CodePub\Models\User
     */
    private $user;
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    public function __construct(BookRepository $book, User $user, CategoryRepository $categoryRepository)
    {
        $this->book = $book;
        $this->user = $user;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $books = $this->book->with('author')->paginate();
        return view('codeedubook::books.index', compact('books', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->categoryRepository->lists('name_trashed', 'id');
        return view('codeedubook::books.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \CodeEduBook\Http\Requests\BookCreateRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookCreateRequest $request)
    {
        $data = $request->all();
        $data['author_id'] = \Auth::user()->id;

        $this->book->create($data);

        $request->session()->flash('message', ['type' => 'success', 'message' => 'Livro cadastrado com sucesso!']);

        $url = $request->get('redirect_to', route('books.index'));
        return redirect()->to($url);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param Book $book
     * @internal param int $id
     */
    public function edit($id)
    {
        $book = $this->book->find($id);
        $this->categoryRepository->withTrashed();
        $categories = $this->categoryRepository->listsWithMutators('name_trashed', 'id');
        return view('codeedubook::books.edit', compact('book', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BookUpdateRequest|Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param Book $book
     * @internal param int $id
     */
    public function update(BookUpdateRequest $request, $id)
    {
        $data = $request->except(['author_id']);
        $this->book->update($data, $id);

        $request->session()->flash('message', ['type' => 'success', 'message' => 'Livro atualizado com sucesso!']);

        $url = $request->get('redirect_to', route('books.index'));
        return redirect()->to($url);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     * @internal param Book $book
     * @internal param int $id
     */
    public function destroy($id)
    {
        $this->book->delete($id);
        \Session::flash('message', ['type' => 'success', 'message' => 'Livro excluído com sucesso!']);
        return redirect()->back();
    }
}

Modules/CodeEduBook/resources/views/trashed/books/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Lixeira de Livros</h3>
                {!! Button::primary('Novo Livro')->asLinkTo(route('books.create')) !!}
            </div>
        </div>

        <br>
        <div class="well well-sm">
            {!! Form::model(compact('search'), ['class' => 'form', 'method' => 'GET']) !!}
            <div class="row">
                <div class="col-sm-12">
                    <div class="input-group">
                        {!! Form::text('search', null, ['class' => 'form-control', 'placeholder' => 'Pesquisar por título, autor ou categoria']) !!}
                        <span class="input-group-btn">
                            {!! Button::withValue('Buscar')->submit() !!}
                      </span>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
        </div>

        <div class="row">
            <div class="col-sm-12">
                @if($books->count() > 0)
                    {!!
                    Table::withContents($books->items())
                               ->striped()
                               ->callback('Ações', function($field, $book) {
                                    $linkView = route('trashed.books.show', $book->id);
                                    $linkRestore = route('books.destroy', $book->id);
                                    $restoreForm = "restore-form-{$book->id}";
                                    $form = Form::open([
                                                'route' => ['trashed.books.update', 'book' => $book->id],
                                                'method' => 'PUT', 'class' => 'hide no-margin', 'id' => $restoreForm
                                            ]).
                                            Form::hidden('redirect_to', URL::previous()).
                                            Form::close();
                                    $anchorRestore = Button::primary('Restaurar')->asLinkTo($linkRestore)->addAttributes([
                                        'onclick' => "event.preventDefault();document.getElementById(\"$restoreForm\").submit();"
                                    ])->small();

                                    return  '<ul class="list-unstyled list-inline no-margin">'.
                                            '<li>'. Button::withValue('Ver')->asLinkTo($linkView)->small() .'</li>'.
                                            '<li>'. $anchorRestore .'</li>'.
                                            '</ul>'.
                                            $form;
                               })
                    !!}

                    {!! $books->links() !!}
                @else
                    <div class="alert alert-info">Lixeira vazia</div>
                @endif
            </div>
        </div>
    </div>

@endsection

Modules/CodeEduBook/resources/views/trashed/books/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Livro - {{ $book->title }}</h3>
                {!! Button::withValue('Voltar')->asLinkTo(route('trashed.books.index')) !!}
            </div>
        </div>

        <br>
        <div class="row">
            <div class="col-sm-12">
                <ul class="list-group">
                    <li class="list-group-item"><strong>Título</strong></li>
                    <li class="list-group-item">{{ $book->title }}</li>
                    <li class="list-group-item"><strong>Subtítulo</strong></li>
                    <li class="list-group-item">{{ $book->subtitle }}</li>
                    <li class="list-group-item"><strong>Autor</strong></li>
                    <li class="list-group-item">{{ $book->author->name }}</li>
                    <li class="list-group-item"><strong>Preço</strong></li>
                    <li class="list-group-item">{{ $book->price }}</li>
                    <li class="list-group-item"><strong>Categorias</strong></li>
                    <li class="list-group-item">{{ $book->categories->implode('name_trashed', ', ') }}</li>
                </ul>
            </div>
        </div>
    </div>

@endsection